const images = {
    wrapperSplash: require('./wrapperSplash.png'),
    signature: require('./signature.png'),
    iconBack: require('./iconBack.png'),
    hanoi: require('./hanoi.png'),
    iconSearch: require('./iconSearch.png'),
    vietranh: require('./vietanh.png'),
    note2: require('./note2.png'),
    iconMore: require('./ic_more.png'),
    isCoffee: require('./isCoffee.png'),
    isHome: require('./isHome.png'),
    isUser: require('./isUser.png'),
    activeCoffee: require('./activeCoffee.png'),
    activeHome: require('./activeHome.png'),
    activeUser: require('./activeUser.png'),
    icTime: require('./icTime.png'),
    backDrop: require('./backDrop.png'),
    radio: require('./radio.png'),
    pause: require('./pause.png'),
    repeat: require('./repeat.png'),
    shuffle: require('./shuffle.png'),
    skipback: require('./skipback.png'),
    skipforward: require('./skipforward.png'),
    topRadio: require('./topRadio.png'),
    wrapButtonRadio: require('./wrapButtonRadio.png'),
    bgTimeRadio: require('./bgTimeRadio.png'),
    bgTrackRadio: require('./bgTrackRadio.png'),
    ic_copydown: require('./ic_copydown.png'),
    ic_down: require('./ic_down.png'),
    ic_heart: require('./ic_heart.png'),
    ic_plus: require('./ic_plus.png'),

};

export default images;