
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_ACTION_SUCCESS = 'LOGIN_ACTION_SUCCESS';
export const LOGIN_ACTION_ERROR = 'LOGIN_ACTION_ERROR';

export const GET_LIST_MUSIC = 'GET_LIST_MUSIC';
export const GET_SUCCSESS_LIST_MUSIC = 'GET_SUCCSESS_LIST_MUSIC';
export const GET_ERROR_LIST_MUSIC = 'GET_ERROR_LIST_MUSIC';